GET http://localhost:5000/api/v1/user/asasasas

###

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "password"
}
###

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}

###

GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlX2NvZGUiOiJSMiIsImlhdCI6MTcwMDU1MTEwMCwiZXhwIjoxNzAwOTgzMTAwfQ.SMYH0LJrWqYQA_G23Qo9JvnoCw_NupuLSvRuFROT1IY

###

GET http://localhost:5000/api/v1/insert/

###

GET http://localhost:5000/api/v1/book/?available[]=5&available[]=10

