GET http://localhost:5000/api/v1/user/asasasas

###

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}
###

POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "password"
}

###

GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlX2NvZGUiOiJSMyIsImlhdCI6MTcwMDkxNDc5MCwiZXhwIjoxNzAwOTE0Nzk1fQ.I7d5FuayE52VIRHbvj7uEet_mjmEr63VTXAQY2GdYtY

###

GET http://localhost:5000/api/v1/insert/

###

GET http://localhost:5000/api/v1/book/?available[]=5&available[]=10

